### ISSUE TITLE
Import Zeilen nicht überschreiben

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#1016]
## Describe the bug

Wir haben eine Liste die wir importiert haben mit dem Import im System vergleichen wollen und dabei ist aufgefallen, dass die Liste im Import keine abgeglichenen Fälle anzeigt. Die importierte Liste (Excel auf dem Laptop gespeichert) zeigt aber 104 Fälle an.
Evtl. liegt es ja daran, dass die Fälle danach erneut abgeglichen worden sind, also dann im "alten" Import verschwinden und nur noch im neuen Import als abgeglichen angezeigt werden.

Link zu einem Import:
https://covid19-tracing.ch/inbox/imports/e24695fd-cdac-4168-8f70-a72f68acca90

Die Excel Liste wurde in der Mail an Jony verschickt.

## TODO

* [x] Create Link Table (many to many) between row and import
* [x] Migrate old import foreign key to use link table
* [x] UI
  - show latest import in header
  - show all imports in detail view
* [x] When importing a row keep checking if duplicate
  - if duplicate: only create link
  - if not duplicate: create row and link
  - Change `on_conflict` to `{:replace, [:updated_at]}`
  - Change `returning` to `[:uuid]`
  - Add `Ecto.Multi.insert_all` to add all the links for the rows
* [x] Create Trigger that deletes all rows that are not linked to any import

## References

* https://app.forecast.it/project/P-205/scoping/T3578

**Comment by maennchen** [comment]
Auszug von Antowrt-Email zum Thema:

> Das ist so erwartet. Wie du schon bereits herausgefunden hast, werden identische Zeilen bei einem neuen Import verschoben. Dies steht auch hier: https://covid19-tracing.ch/inbox/imports/new
> 
> Eine solche Zeile ist z.B. diese: https://covid19-tracing.ch/inbox/rows/89177863-cd21-44d0-9989-f445719ffdcd

**Comment by St-Annette** [comment]
@maennchen Ja stimmt, ich hatte es mal gelesen, aber wieder vergessen, weil wir es bisher nicht gebraucht haben. Wäre es möglich dass das nicht passiert? So kann man leider nicht mehr nachvollziehen wie viele Fälle bei einem früheren Import importiert worden sind.

**Comment by maennchen** [comment]
@St-Annette Ich hane das damals so gelöst, weil es sonst relativ komplex ist.

Ich überlege mir eine Lösung dazu und mache eine Schätzung. Rückwirkend wird es aber warscheinlich nicht gehen.

**Comment by St-Annette** [comment]
@maennchen Ok Danke Dir. Rückwirkend ist ok wenn es nicht klappt. Aber für später wäre es super wenn man das nachvollziehen könnte.

**Comment by maennchen** [comment]
Schätzung: 4 - 6 Stunden

**Comment by maennchen** [comment]
@atoncetti It seems we have an issue in the migration.

```
16:50:05.742 [notice] Application hygeia exited: exited in: Hygeia.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (Postgrex.Error) ERROR 23502 (not_null_violation) null value in column "inserted_at" of relation "row_links" violates not-null constraint

    table: row_links
    column: inserted_at

Failing row contains (58f1d7b8-c234-40ba-96cf-448a0bfd2f32, c9776ae9-487a-417e-8c73-8f2c7686dba1, null, null).
            (ecto_sql 3.7.2) lib/ecto/adapters/sql.ex:760: Ecto.Adapters.SQL.raise_sql_call_error/1
            (elixir 1.13.3) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
            (ecto_sql 3.7.2) lib/ecto/adapters/sql.ex:852: Ecto.Adapters.SQL.execute_ddl/4
            (ecto_sql 3.7.2) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
            (ecto_sql 3.7.2) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
            (elixir 1.13.3) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
            (ecto_sql 3.7.2) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
            (ecto_sql 3.7.2) lib/ecto/migration/runner.ex:280: Ecto.Migration.Runner.perform_operation/3
```

**Comment by maennchen** [comment]
@rebecca-br Wir haben noch ein Problem beim Deployment von diesem Issue. Wir müssen das zuerst flicken, bevor wir den Test Release erfolgreich machen können.

Daher benötigen wir Morgen noch um den Release zu machen.

**Comment by rebecca-br** [comment]
@maennchen ja das passt. Danke

**Comment by maennchen** [comment]
@rebecca-br / @saanni / @St-Annette Bereit zum testen.

Am besten lädt ihr die selbe Liste 2 mal hoch. Dann solltet ihr das folgende sehen:
* Die Zeile wird bei beiden Imports angezeigt
* Der 1. Import wird geschlossen, da alle Zeilen im nächsten Import weiter bearbeitet werden.
* Bei der Detail-Ansicht der Zeile hat es eine neue Box `Importe, die diese Zeile importiert haben`. Darin sieht man wo die Zeile überall Importiert wurde.
* Im Header der Zeile wird jeweils der neuste Import angezeigt.

**Comment by rebecca-br** [comment]
@maennchen @St-Annette  ich glaube fast, dass müssen wir nochmals anschauen und besprechen. Ich habe eine Liste mit 3 Fällen importiert. Wenn ich exakt die selbe Liste nochmals importiere, werden die Fälle auf abgeglichen gesetzt. Dann habe ich eine neue Liste importiert mit 12 Fällen. Da sind die 3 Fälle der ersten Liste auch mit dabei. Dann wird aber gar nichts auf abgeglichen gesetzt. Demzufolge muss man die Fälle die zuvor importiert worden sind, nochmals abgleichen....

**Comment by maennchen** [comment]
@rebecca-br Ist dieses Feature ok? (Ich glaube wir waren telefonisch einverstanden das das so stimmt.)

**Comment by rebecca-br** [comment]
@maennchen ja das passt. Das hat ja funktioniert.
