### ISSUE TITLE
keine KP's mehr im Autotracing 

### ISSUE THREAD

**Issue by rebecca-br** [jshmrtn/hygeia#1189]
## Is your feature request related to a problem? Please describe.
Auf Grund der Entscheidungen vom Bund, gibt es keine Kontaktpersonen mehr. Laufende KP Phasen werden am Tag x beendet. 
AT Problem KP Einsendungen müsste dann deaktiviert werden. 

## Describe the solution you'd like
~~Wenn der Benutzer das AT ausfüllt, könnten wir beim Punkt Kontaktpersonen einen Text anzeigen.~~

~~**Auf Grund der Entscheidungen vom Bund gibt es ab (Datum) keinen Kontaktpersonen mehr.**~~

Skip Contact Person step if disabled, no message.

Am Schluss vom AT Tracing muss der Button mit KP's Einsenden deaktiviert werden. 

## TODO

* [x] Create Quarantine Enabled Boolean in Config
* [x] Conditionally Show things, do not delete them.
* [ ] When enabled --> OneOff end all quarantines
* [ ] When enabled --> OneOff resolve all AutoTracing Problems

## References

* https://app.forecast.it/project/P-205/scoping/T3490

**Comment by janmrnak** [comment]
**OneOff end all quarantines:**

SELECT SET_CONFIG('versioning.originator_id', '', true);
SELECT SET_CONFIG('versioning.origin', 'migration', true);
UPDATE
  cases update_case
  SET
      phases = ARRAY_REPLACE(
          update_case.phases,
          replace_case.search_phase,
          replace_case.replace_phase
      )
  FROM (
    SELECT
      cases.uuid AS case_uuid,
      people_with_data.uuid AS person_uuid,
      people_with_data.first_name AS first_name,
      people_with_data.last_name AS last_name,
      people_with_data.email AS email,
      people_with_data.mobile AS mobile,
      people_with_data.landline AS landline,
      active_phases -> 'details' ->> '__type__' AS phase_type,
      (active_phases ->> 'end')::date AS original_end_date,
      CURRENT_DATE AS new_end_date,
      active_phases AS search_phase,
      active_phases || JSONB_BUILD_OBJECT(
        'end',
        CURRENT_DATE
        ) AS replace_phase
    FROM cases
    JOIN
      UNNEST(cases.phases) AS active_phases
      ON
	  	active_phases -> 'details' ->> '__type__' = 'possible_index' AND
	 	active_phases ->'details' ->> 'type' = 'contact_person' AND
	  	active_phases ->>'quarantine_order' = 'true' AND
        (active_phases ->> 'end')::date > NOW() AND
        (active_phases ->> 'inserted_at')::timestamp <= '2022-02-02 11:27:00'
    JOIN
      (
        SELECT
          people.uuid,
          people.first_name,
          people.last_name,
          MIN(mobile_contact_methods->>'value') AS mobile,
          MIN(email_contact_methods->>'value') AS email,
          MIN(landline_contact_methods->>'value') AS landline
        FROM people
        LEFT JOIN
          UNNEST(people.contact_methods) AS mobile_contact_methods
          ON mobile_contact_methods->>'type' = 'mobile'
        LEFT JOIN
          UNNEST(people.contact_methods) AS email_contact_methods
          ON mobile_contact_methods->>'type' = 'email'
        LEFT JOIN
          UNNEST(people.contact_methods) AS landline_contact_methods
          ON landline_contact_methods->>'type' = 'landline'
        GROUP BY people.uuid
      ) AS people_with_data
      ON people_with_data.uuid = cases.person_uuid
  ) AS replace_case
  WHERE replace_case.case_uuid = update_case.uuid
  RETURNING
      replace_case.case_uuid,
      replace_case.person_uuid,
      replace_case.first_name,
      replace_case.last_name,
      replace_case.email,
      replace_case.mobile,
      replace_case.landline,
      replace_case.phase_type,
      replace_case.original_end_date,
      replace_case.new_end_date;

**Comment by janmrnak** [comment]
**OneOff resolve all AutoTracing Problems:**

        UPDATE auto_tracings
        SET problems = ARRAY_REMOVE(problems, 'possible_index_submission')
        WHERE 'possible_index_submission' = ANY(problems)
   
        UPDATE auto_tracings
        SET solved_problems = ARRAY_REMOVE(solved_problems, 'possible_index_submission')
        WHERE 'possible_index_submission' = ANY(solved_problems)

**Comment by rebecca-br** [comment]
@maennchen @jeremyzahner ab morgen gibt es keine Quarantäne mehr. Laut dem KAA ist es nicht nötig die laufenden Q Phasen anzupassen. Heute ist der letzte Quarantäne Tag für Kontaktpersonen. Wenn wir die Q Phasen anpassen, müssten wir alle laufende Q per 02.02.22 beenden. 
Ab morgen sollte der Punkt im AT Kontaktpersonen deaktiviert sein. Könnt ihr schon einschätzen wie es damit aussieht, ab wann wir das im Live System haben? Laut dem KAA müssen wir mit dem Import heute Abend stoppen, bis wir das umgesetzt haben.

**Comment by maennchen** [comment]
@rebecca-br Die Anpassung der Quarantänen werden wir Heute sicher nicht mehr schaffen. Die Deaktivierung der Links etc. kann ich noch nicht beurteilen.

Ich hakte dich auf dem Laufenden.

**Comment by rebecca-br** [comment]
@maennchen Anpassung der Quarantäne eilt auch nicht. Da wir nicht in der Pflicht sind laufende Q zu beenden.  Wichtig wäre einfach das für die Benutzer das Einsenden von KP's nicht mehr möglich ist.

**Comment by janmrnak** [comment]
@maennchen 
ich glaube das braucht es auch:

UPDATE auto_tracings
SET current_step = 'end'
WHERE current_step = 'contact_persons';

UPDATE auto_tracings
SET last_completed_step = 'transmission'
WHERE last_completed_step = 'contact_persons';

**Comment by maennchen** [comment]
@rebecca-br Mir ist nicht ganz wohl dies ohne einen Testrelease live zu schalten. Ich bereite gerade den Release vor. Du solltest in ca. 20-30 Minuten testen können.

**Comment by rebecca-br** [comment]
@maennchen alles klar, ja das passt.

**Comment by maennchen** [comment]
@rebecca-br Bereit zum testen.

**Comment by rebecca-br** [comment]
@maennchen das hat funktioniert. 👍

**Comment by maennchen** [comment]
@rebecca-br Prod Release ist fertig.

**Comment by rebecca-br** [comment]
@maennchen Danke vielmals
