### ISSUE TITLE
Open Source Hygeia

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#3]
forecast-sg#2262

## TODO before making repo public

* [x] Add License Files #4
* [x] Setup CI / CD #1 
* [x] Connect private Deployment CI #6 

## TODO after making repo public

* [x] Change CI to use `coveralls.github` instead of `coveralls.details`
* [x] Setup Coveralls Account

## TODO anytime

* [ ] Add Docker Push Mirrors quay.io & Docker Hub
* [ ] Add `CONTRIBUTING` guide (mentioning CLA)
