### ISSUE TITLE
Move hospitalizations into own entity instead of embed

### ISSUE THREAD

**Issue by maennchen** [jshmrtn/hygeia#44]
Follow up for #43

## TODO

* [x] Put into separate table
* [x] Migrate Relation in case of organisation merge
* [x] Nilify on organisation delete

**Comment by maennchen** [comment]
@St-Annette 

## Testing

### Organisation löschen

* Bei einem Fall eine Hospitalisierung hinzufügen
* Die referenzierte Organisation löschen
* Beim Fall sollte nun eine Hospitalisation ohne eine ausgewählte Organisation erfasst sein
* Der Fall sollte keinen 404 Fehler anzeigen

### Organisation fusionieren

* Bei einem Fall eine Hospitalisierung hinzufügen
* Die referenzierte Organisation mit einer anderen Organisation fusionieren
* Beim Fall sollte nun eine Hospitalisation mit der neuen Organisation erfasst sein
* Der Fall sollte keinen 404 Fehler anzeigen

## Aufräumen der bereits beschädigten Daten

* Wir entfernen die Organisation bei den Hospitalisierungen welche ins leere zeigen (somit aktuell einen 404 anzeigen)
* Wir fügen eine Notiz ins Protokoll hinzu mit dem Namen der gelöschten Organisation
* Wir schicken euch eine Liste mit den beschädigten Fällen damit diese anhand von diesem Kommentar repariert werden können (Organisation neu auswählen)

Dies werden wir mit https://github.com/jshmrtn/hygeia/discussions/164 & https://github.com/jshmrtn/hygeia/discussions/166 umsetzen.

**Comment by St-Annette** [comment]
@maennchen Löschen und fusionieren funktioniert wie beschrieben. Man kann ohne Probleme weiterhin auf den Fall zugreifen. 
Die Lösung zum Aufräumen finde ich auch sehr gut :)

**Comment by maennchen** [comment]
@St-Annette Super, danke :)

**Comment by maennchen** [comment]
@St-Annette Habe die beschädigten Daten exportier und an @jeremyzahner geschickt damit er dir das File weitergeben kann.
