### ISSUE TITLE
Impfdurchbruch Export

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#544]
## Is your feature request related to a problem? Please describe.
Für die Kantonsärztin müssten die Impfdurchbruch exportiert werden. Es sollte möglich sein einen Zeitraum mit den Impfversagern in dieser Zeit und die Liste zu exportieren

## Describe the solution you'd like
Daten:
- Impftermine
- Geburtsdatum Index
- Symptomstart/Testdatum

## TODO

* [x] Add new export format to tenant export (same permissions as BAG exports)
* [x] Export (CSV) contains a row for every case that matches the following criteria
  - Person has set vaccinated to true
  - Person has at least two vaccinations
  - Case Phase Index Inserted at >= 2nd vaccination date
* [x] Contains the following columns
  - Person ID
  - Person Firstname
  - Person Lastname
  - Person Birthday
  - Vaccination Name
  - Vaccination Date 1
  - Vaccination Date 2
  - Vaccination Date 3
  - Case ID
  - Case Clinical Symptom Start
  - Date of last Test in Case
  - Symptoms (Translated to German, joined with a `, `)

## References
- https://trello.com/c/dGroV1I9/869-impfversager-export
- https://app.forecast.it/project/P-205/scoping/T2721

**Comment by rebecca-br** [comment]
@jeremyzahner könntest du bitte mal prüfen, ob wir einen Export für diese Daten aus dem Hygeia machen können. 

- Name vom Index 
- Geb. Datum 
- Impfstoff 
- 1. Impftermin 
- 2. Impftermin
- 3. Impftermin 
- Symptombeginn 
- Testdatum
- Verlauf, Symptome

Zusätzlich bräuchten wir die Zahlen der Impfdurchbrüche pro Tag für den Zustand Tracing, dies müsste jedoch über den Filter machbar sein.

**Comment by jeremyzahner** [comment]
@maennchen @atoncetti 

I can't get any data in the exports.

Test Case:
https://staging.covid19-tracing.ch/cases/8ef33b72-7586-4004-abf8-8fcd471b1f97

**Comment by maennchen** [comment]
Caused by:

```
Postgrex.Error: ERROR 22023 (invalid_parameter_value) cannot cast jsonb null to type boolean
  File "lib/db_connection.ex", line 1726, in DBConnection.stream_fetch/3
  File "lib/stream.ex", line 1531, in Stream.do_resource/5
  File "lib/stream.ex", line 1719, in Enumerable.Stream.do_each/4
  File "lib/stream.ex", line 880, in Stream.do_transform/5
  File "lib/stream.ex", line 1719, in Enumerable.Stream.do_each/4
  File "lib/stream.ex", line 956, in Stream.do_enum_transform/7
  File "lib/stream.ex", line 880, in Stream.do_transform/5
  File "lib/enum.ex", line 2431, in Enum.reduce_while/3
```

**Comment by jeremyzahner** [comment]
@St-Annette @rebecca-br @saanni Bereit zum testen.

**Comment by rebecca-br** [comment]
@jeremyzahner wie können wir das testen?

**Comment by maennchen** [comment]
@rebecca-br Erfasse mehrere Fälle, die du als Impfdurchbruch erwartest oder auch nicht. Dann kannst du beim Mandanten-Export einen Impfdurchbruch Export machen und schauen ob die richtigen Fälle drinn sin.

Achtung: Wir prüfen, ob der Fall (Anhand von den Test-Daten oder falls nicht vorhanden dem Erstellungsdatum) vor oder nach den Impfungen passiert ist. Daher musst du etwas aufpassen, dass du gültige Daten eingibst.

**Comment by rebecca-br** [comment]
@maennchen ich habe im Testsystem keine Möglichkeit beim Mandanten etwas anzuwählen. 
<img width="1215" alt="Bildschirmfoto 2021-12-03 um 11 07 41" src="https://user-images.githubusercontent.com/93326696/144584968-e73af591-d0a7-4361-9c63-b4c18f0058ae.png">

**Comment by maennchen** [comment]
@rebecca-br Ich habe dir etwas mehr Berechtigungen gegeben für Staging. Wie sieht es jetzt aus?

**Comment by rebecca-br** [comment]
@maennchen Danke jetzt sieht es schon besser aus 👍

**Comment by maennchen** [comment]
@rebecca-br Heisst das, dass du fertig getestet hast oder bist du noch drann?

**Comment by rebecca-br** [comment]
@maennchen das hat funktioniert. Ich habe alles Infos auf der Liste.

**Comment by rebecca-br** [comment]
@maennchen etwas ist mir noch aufgefallen. der Janssen Impfstoff taucht bei den Impfdurchbrüchen nicht auf der Liste auf. COVID-19 Vaccine Janssen (Johnson & Johnson) wird 1 mal geimpft. Wenn sie nach 22 Tagen positiv werden, gelten diese auch als Impfdurchbruch. Evlt. Müssen wir beim Name Impfstoff eine Liste mit der Auswahl der Impfstoffe machen. Dann hätten wir die Daten immer gleich im System.

**Comment by maennchen** [comment]
@jeremyzahner / @St-Annette Für neue Anforderungen sollten wir ein neues Issue erstellen. sonst gibt das ein Durcheinander.

**Comment by maennchen** [comment]
@St-Annette / @jeremyzahner Ich gehe davon aus, dass Ihr mit den Release nicht auf dies warten möchtet. Können wir daher ein neues Issue erstellen?

**Comment by St-Annette** [comment]
@maennchen Ja genau ich erstelle ein neues Issue

**Comment by maennchen** [comment]
@St-Annette ich bin beriets drann. 1 minute :)

**Comment by St-Annette** [comment]
@maennchen bitte den Release auf ab 17:30 Uhr heute abend ansetzen. Geht das?

**Comment by maennchen** [comment]
@St-Annette Moved to https://github.com/jshmrtn/hygeia/issues/980
