### ISSUE TITLE
Fall-Liste Filter: Kanton

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#579]
**Is your feature request related to a problem? Please describe.**
Fälle von AI und AR müssen derzeit vorgezogen werden
Es gibt in Hygeia keine Möglichkeit diese Fälle zu finden.

**Describe the solution you'd like**
Filter Mandant: AR, AI und SG

**TODO**

* [ ] Add Tenant Filter
* [ ] Prefill every canton where a user is supervisor/tracer
* [ ] Make it possible for superusers to select unmanaged cantons
* [ ] Add same for Person List

**References**
- https://trello.com/c/bEa0YOxC/880-fall-liste-filter-kanton
- https://app.forecast.it/project/P-205/scoping/T2725

**Comment by rebecca-br** [comment]
Hat sich mit dem neuen Filter schon erledigt.
