### ISSUE TITLE
Autotracing: Adresse Isolation

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#623]
**Is your feature request related to a problem? Please describe.**
Die Option Isolationsadresse ist für manche User verwirrend.

**Describe the solution you'd like**
"Verbringen Sie Ihre Isolation an einem anderen Ort?"
Option: ja/nein
Falls ja:
Adresse kann eingetragen werden (andernfalls ist diese Option nicht sichtbar)

**References**
- https://app.forecast.it/project/P-205/scoping/T2753

**TODO**

* [x] Add Boolean (also for tracer, not only auto tracing)
* [x] Conditionally show address (both tracer / auto tracing)
* [x] Migrate field to true when address is present

**Comment by maennchen** [comment]
@St-Annette Bitte jeweils das Issue nicht assignen. Das machen wir sobald wir Arbeit verteilen etc.

**Comment by maennchen** [comment]
@St-Annette Die Typen sind gemäss dem BAG MED umgestzt. Zusätzliche können wir nicht einfach einbauen. Bitte mach ein separates Issue dafür.

@atoncetti TODO:

* [ ] Remove `home` from select since that is implied by choosing `no`  for another address.
* [ ] Only make `location_details` required, if `other` is selected
