### ISSUE TITLE
Anpassungen Inkonsistentes Phasendatum

### ISSUE THREAD

**Issue by St-Annette** [jshmrtn/hygeia#859]
## Is your feature request related to a problem? Please describe.

Der Zeitraum in dem das AT-Problem "Inkonsistentes Phasendatum" auftritt muss angepasst werden.

## Describe the solution you'd like
Zeitraum bitte auf 6 Tage ab Test anpassen (statt bisher 4 Tage)

## TODO

**Meeting 23.11.2021:**

* [x] Remove Inconsistent Auto Tracing Problem
* [x] Remove warning in Auto Tracing Header
* [x] Modify warning under date field to a message like `Are you sure? This date is unusual far in the past.` (If date more than 5 days away from first test date)
* [x] Calculate phase end date as `max(symptom_start_date, today - 5) + 10`

## Describe alternatives you've considered

* Increasing the threshold for the problem. This was deemed unsatisfactory.

## References

* https://app.forecast.it/project/P-205/scoping/T3006

**Comment by St-Annette** [comment]
@maennchen Es sind jetzt 7 Tage (Test ist Tag 1 und Problem sollte ab Tag 6 ausgelöst werden). Beispiel: Test am 22.11. Problem sollte ausgelöst werden ab dem 17. 
Im Moment wird es ab dem 16. ausgelöst. Aber über dieses Issue wollte Rebecca heute Abend bei dem Call sowieso sprechen, deshalb kann es einfach erst mal liegen bleiben.

**Comment by maennchen** [comment]
Previous Implementation was reversed so that it is not deployed to prod.

**Comment by jeremyzahner** [comment]
@rebecca-br @saanni @St-Annette Das kann getestet werden.

**Comment by rebecca-br** [comment]
@maennchen habe das getestet. Symptombeginn 24.11.21 Testdatum 03.12.21 das stimmt noch nicht. Das Dokument wurde dann erstellt vom 24.11.21 bis 07.12.21.

<img width="799" alt="Bildschirmfoto 2021-12-03 um 14 13 41" src="https://user-images.githubusercontent.com/93326696/144608662-d25110cf-3d14-41a6-9b28-ebb04e556269.png">

Im Dokument müsste dann der 28.11.21 bis 07.12.21 stehen. Wenn wir da ja 5 Tage zurück gehen. Ansonsten wäre die Isolation mehr als 10 Tage.

**Comment by maennchen** [comment]
@rebecca-br Besser?

**Comment by rebecca-br** [comment]
@maennchen ja jetzt stimmt es. Und das Dokument wird korrekt ausgestellt.
